### ISSUE TITLE
FR: Scatterplot Improvements

### ISSUE THREAD

**Issue by kgaspard** [llooker/viz-histogram-marketplace#1]
A major EMEA retail/CPG customer would love to see the following improvements to the viz:

- Categorising points by colour, w/ legend
   - Should be built into Vega
   - No need for selector, can just do "second dim is category"
- Have scatterplot in quadrants - so reference line for X and Y
   - Customer wants Median, having Mean would be useful, having percentiles would be ideal but not needed for now
- Being able to trigger crossfiltering by point
   - Just dimensions applied as cross-filters, not X and Y values
   - Histograms themselves not important
- Add labels of dimensions on points
   - Ideally can select dimension, but first dimension is fine (as other dimensions show up in the tooltip anyway)

**Comment by kgaspard** [comment]
Update on point #2 above. It turns out percentiles are actually important. So it's still a single reference  line on the X and Y axis, but with a percentile number selector from 0 to 1 for each of X and Y. And if the user select say 0.3 for X, then we have 
~30% of the points to the left and ~70% to the right

**Comment by thomasbanghart** [comment]
Features added in PR #4 -- let us know if you need anything else 👍
